"""add product uoms

Revision ID: 190c31e3b133
Revises: ef61eeac70e4
Create Date: 2025-12-03 11:29:00.126830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '190c31e3b133'
down_revision: Union[str, None] = 'ef61eeac70e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_uoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('uom_name', sa.String(length=100), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'uom_name', name='uq_product_uom_name'),
    sa.UniqueConstraint('tenant_id', 'barcode', name='uq_tenant_barcode')
    )
    op.create_index('ix_product_uoms_barcode', 'product_uoms', ['barcode'], unique=False)
    op.create_index(op.f('ix_product_uoms_id'), 'product_uoms', ['id'], unique=False)
    op.create_index('ix_product_uoms_product_id', 'product_uoms', ['product_id'], unique=False)
    op.create_index('ix_product_uoms_tenant_id', 'product_uoms', ['tenant_id'], unique=False)
    op.add_column('products', sa.Column('base_unit', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'base_unit')
    op.drop_index('ix_product_uoms_tenant_id', table_name='product_uoms')
    op.drop_index('ix_product_uoms_product_id', table_name='product_uoms')
    op.drop_index(op.f('ix_product_uoms_id'), table_name='product_uoms')
    op.drop_index('ix_product_uoms_barcode', table_name='product_uoms')
    op.drop_table('product_uoms')
    # ### end Alembic commands ###
