"""add depositors and warehouses

Revision ID: 2ec6a8f92d9e
Revises: a357d02a4048
Create Date: 2025-12-02 22:08:51.925463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ec6a8f92d9e'
down_revision: Union[str, None] = 'a357d02a4048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
