"""initial_schema

Revision ID: 475da3ba7410
Revises: 
Create Date: 2025-12-04 13:39:47.983721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '475da3ba7410'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Tenants Table
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    
    # 2. Depositors Table
    op.create_table('depositors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_tenant_depositor_code')
    )
    op.create_index('ix_depositors_code', 'depositors', ['code'], unique=False)
    op.create_index(op.f('ix_depositors_id'), 'depositors', ['id'], unique=False)
    op.create_index('ix_depositors_tenant_id', 'depositors', ['tenant_id'], unique=False)
    
    # 3. Location Definitions Tables
    op.create_table('location_type_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_tenant_location_type_code')
    )
    op.create_index('ix_location_type_definitions_code', 'location_type_definitions', ['code'], unique=False)
    op.create_index(op.f('ix_location_type_definitions_id'), 'location_type_definitions', ['id'], unique=False)
    op.create_index('ix_location_type_definitions_tenant_id', 'location_type_definitions', ['tenant_id'], unique=False)
    
    op.create_table('location_usage_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_tenant_location_usage_code')
    )
    op.create_index('ix_location_usage_definitions_code', 'location_usage_definitions', ['code'], unique=False)
    op.create_index(op.f('ix_location_usage_definitions_id'), 'location_usage_definitions', ['id'], unique=False)
    op.create_index('ix_location_usage_definitions_tenant_id', 'location_usage_definitions', ['tenant_id'], unique=False)
    
    # 4. UOM Definitions
    op.create_table('uom_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_tenant_uom_code')
    )
    op.create_index('ix_uom_definitions_code', 'uom_definitions', ['code'], unique=False)
    op.create_index(op.f('ix_uom_definitions_id'), 'uom_definitions', ['id'], unique=False)
    op.create_index('ix_uom_definitions_tenant_id', 'uom_definitions', ['tenant_id'], unique=False)
    
    # 5. Users Table - שינוי קריטי: tenant_id הוא כעת Nullable
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True), # שונה ל-True כדי לאפשר Super Admin
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'PICKER', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    
    # 6. Warehouses Table
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_tenant_warehouse_code')
    )
    op.create_index('ix_warehouses_code', 'warehouses', ['code'], unique=False)
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index('ix_warehouses_tenant_id', 'warehouses', ['tenant_id'], unique=False)
    
    # 7. Products Table
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('depositor_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.Column('base_uom_id', sa.Integer(), nullable=True),
    sa.Column('custom_attributes', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_uom_id'], ['uom_definitions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['depositor_id'], ['depositors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'sku', name='uq_tenant_sku')
    )
    op.create_index('ix_products_depositor_id', 'products', ['depositor_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index('ix_products_sku', 'products', ['sku'], unique=False)
    op.create_index('ix_products_tenant_id', 'products', ['tenant_id'], unique=False)
    
    # 8. User Settings
    op.create_table('user_table_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'table_name', name='uq_user_table_name')
    )
    op.create_index(op.f('ix_user_table_settings_id'), 'user_table_settings', ['id'], unique=False)
    op.create_index('ix_user_table_settings_table_name', 'user_table_settings', ['table_name'], unique=False)
    op.create_index('ix_user_table_settings_user_id', 'user_table_settings', ['user_id'], unique=False)
    
    # 9. Zones
    op.create_table('zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'warehouse_id', 'code', name='uq_zone_code_per_warehouse')
    )
    op.create_index(op.f('ix_zones_tenant_id'), 'zones', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_zones_warehouse_id'), 'zones', ['warehouse_id'], unique=False)
    
    # 10. Locations
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('aisle', sa.String(length=50), nullable=False),
    sa.Column('bay', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('slot', sa.String(length=50), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('usage_id', sa.Integer(), nullable=False),
    sa.Column('pick_sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['location_type_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usage_id'], ['location_usage_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'name', name='uq_location_name_per_warehouse')
    )
    op.create_index(op.f('ix_locations_tenant_id'), 'locations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_locations_type_id'), 'locations', ['type_id'], unique=False)
    op.create_index('ix_locations_usage_id', 'locations', ['usage_id'], unique=False)
    op.create_index(op.f('ix_locations_warehouse_id'), 'locations', ['warehouse_id'], unique=False)
    op.create_index('ix_locations_zone_id', 'locations', ['zone_id'], unique=False)
    
    # 11. Product UOMs
    op.create_table('product_uoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('uom_id', sa.Integer(), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('barcode', sa.String(length=255), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uom_id'], ['uom_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'uom_id', name='uq_product_uom_id'),
    sa.UniqueConstraint('tenant_id', 'barcode', name='uq_tenant_barcode')
    )
    op.create_index('ix_product_uoms_barcode', 'product_uoms', ['barcode'], unique=False)
    op.create_index(op.f('ix_product_uoms_id'), 'product_uoms', ['id'], unique=False)
    op.create_index('ix_product_uoms_product_id', 'product_uoms', ['product_id'], unique=False)
    op.create_index('ix_product_uoms_tenant_id', 'product_uoms', ['tenant_id'], unique=False)
    
    # ==========================================
    # SEED DATA INSERTION (Auto-Setup)
    # ==========================================
    
    # 1. יצירת דייר ראשי (System Tenant)
    op.get_bind().execute(sa.text("""
        INSERT INTO tenants (id, name, created_at)
        VALUES (1, 'LogiSnap System', NOW());
    """))
    
    # 2. איפוס ה-Sequence של tenants כדי שלא יתחיל מ-1 שוב
    op.get_bind().execute(sa.text("""
        SELECT setval('tenants_id_seq', (SELECT MAX(id) FROM tenants));
    """))

    # 3. יצירת משתמש אדמין (סיסמה: 123456)
    # Hash generated with bcrypt for "123456"
    op.get_bind().execute(sa.text("""
        INSERT INTO users (tenant_id, email, password_hash, role, full_name, created_at)
        VALUES (1, 'admin@logisnap.com', '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWrn96pzvPn/7qlq4.zEt.k.D5N/26', 'ADMIN', 'System Admin', NOW());
    """))

    # 4. הגדרות ברירת מחדל ל-Location Types/Usages עבור הדייר הראשי
    op.get_bind().execute(sa.text("""
        INSERT INTO location_type_definitions (tenant_id, code, name, created_at, updated_at)
        SELECT id, 'SHELF', 'Shelf', NOW(), NOW() FROM tenants WHERE id = 1
        UNION ALL
        SELECT id, 'PALLET_RACK', 'Pallet Rack', NOW(), NOW() FROM tenants WHERE id = 1
        UNION ALL
        SELECT id, 'FLOOR', 'Floor', NOW(), NOW() FROM tenants WHERE id = 1;
    """))
    
    op.get_bind().execute(sa.text("""
        INSERT INTO location_usage_definitions (tenant_id, code, name, created_at, updated_at)
        SELECT id, 'PICKING', 'Picking', NOW(), NOW() FROM tenants WHERE id = 1
        UNION ALL
        SELECT id, 'STORAGE', 'Storage', NOW(), NOW() FROM tenants WHERE id = 1;
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_uoms_tenant_id', table_name='product_uoms')
    op.drop_index('ix_product_uoms_product_id', table_name='product_uoms')
    op.drop_index(op.f('ix_product_uoms_id'), table_name='product_uoms')
    op.drop_index('ix_product_uoms_barcode', table_name='product_uoms')
    op.drop_table('product_uoms')
    op.drop_index('ix_locations_zone_id', table_name='locations')
    op.drop_index(op.f('ix_locations_warehouse_id'), table_name='locations')
    op.drop_index('ix_locations_usage_id', table_name='locations')
    op.drop_index(op.f('ix_locations_type_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_tenant_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_zones_warehouse_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_tenant_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index('ix_user_table_settings_user_id', table_name='user_table_settings')
    op.drop_index('ix_user_table_settings_table_name', table_name='user_table_settings')
    op.drop_index(op.f('ix_user_table_settings_id'), table_name='user_table_settings')
    op.drop_table('user_table_settings')
    op.drop_index('ix_products_tenant_id', table_name='products')
    op.drop_index('ix_products_sku', table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index('ix_products_depositor_id', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_warehouses_tenant_id', table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_index('ix_warehouses_code', table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_uom_definitions_tenant_id', table_name='uom_definitions')
    op.drop_index(op.f('ix_uom_definitions_id'), table_name='uom_definitions')
    op.drop_index('ix_uom_definitions_code', table_name='uom_definitions')
    op.drop_table('uom_definitions')
    op.drop_index('ix_location_usage_definitions_tenant_id', table_name='location_usage_definitions')
    op.drop_index(op.f('ix_location_usage_definitions_id'), table_name='location_usage_definitions')
    op.drop_index('ix_location_usage_definitions_code', table_name='location_usage_definitions')
    op.drop_table('location_usage_definitions')
    op.drop_index('ix_location_type_definitions_tenant_id', table_name='location_type_definitions')
    op.drop_index(op.f('ix_location_type_definitions_id'), table_name='location_type_definitions')
    op.drop_index('ix_location_type_definitions_code', table_name='location_type_definitions')
    op.drop_table('location_type_definitions')
    op.drop_index('ix_depositors_tenant_id', table_name='depositors')
    op.drop_index(op.f('ix_depositors_id'), table_name='depositors')
    op.drop_index('ix_depositors_code', table_name='depositors')
    op.drop_table('depositors')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###