"""add depositor to products

Revision ID: ef61eeac70e4
Revises: 2ec6a8f92d9e
Create Date: 2025-12-02 22:32:32.832593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef61eeac70e4'
down_revision: Union[str, None] = '2ec6a8f92d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depositors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('contact_info', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_tenant_depositor_code')
    )
    op.create_index('ix_depositors_code', 'depositors', ['code'], unique=False)
    op.create_index(op.f('ix_depositors_id'), 'depositors', ['id'], unique=False)
    op.create_index('ix_depositors_tenant_id', 'depositors', ['tenant_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_tenant_warehouse_code')
    )
    op.create_index('ix_warehouses_code', 'warehouses', ['code'], unique=False)
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index('ix_warehouses_tenant_id', 'warehouses', ['tenant_id'], unique=False)
    op.add_column('products', sa.Column('depositor_id', sa.Integer(), nullable=True))
    op.create_index('ix_products_depositor_id', 'products', ['depositor_id'], unique=False)
    op.create_foreign_key(None, 'products', 'depositors', ['depositor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index('ix_products_depositor_id', table_name='products')
    op.drop_column('products', 'depositor_id')
    op.drop_index('ix_warehouses_tenant_id', table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_index('ix_warehouses_code', table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index('ix_depositors_tenant_id', table_name='depositors')
    op.drop_index(op.f('ix_depositors_id'), table_name='depositors')
    op.drop_index('ix_depositors_code', table_name='depositors')
    op.drop_table('depositors')
    # ### end Alembic commands ###
